export type PostSection =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'callout'; title: string; text: string }
  | { type: 'cta_inline'; label: string; href: string; desc: string };

export interface Post {
  slug: string;
  title: string;
  desc: string;
  cat: string;
  date: string;
  isoDate: string;
  readTime: string;
  iconColor: string;
  bg: string;
  metaTitle: string;
  metaDesc: string;
  featured?: boolean;
  relatedService?: { label: string; href: string };
  body: PostSection[];
}

export const posts: Post[] = [
  {
    slug: 'why-google-ads-arent-converting',
    title: "Why Your Google Ads Aren't Converting (And the Exact Fix We Use for Every Client)",
    desc: 'Most small business campaigns waste 60% of their budget on the wrong keywords. We break down the most common mistakes and the step-by-step fix that works.',
    cat: 'Google Ads',
    date: 'May 2, 2026',
    isoDate: '2026-05-02',
    readTime: '8 min read',
    iconColor: '#1a6eff',
    bg: '#eef3ff',
    featured: true,
    relatedService: { label: 'Google Ads Management', href: '/services/google-ads' },
    metaTitle: "Why Your Google Ads Aren't Converting",
    metaDesc: 'Most small business Google Ads campaigns waste 60% of their budget. Here are the exact mistakes we find in every audit — and how to fix them fast.',
    body: [
      { type: 'p', text: "If you're running Google Ads and not seeing results, you're not alone. The majority of small business campaigns we audit are burning through budget on traffic that was never going to convert — and most owners have no idea it's happening." },
      { type: 'p', text: "After auditing dozens of campaigns for businesses across Daytona Beach and Volusia County, we've found the same five mistakes over and over. Here's what they are and exactly how to fix them." },
      { type: 'h2', text: 'Mistake #1: Using Broad Match Keywords Without Controls' },
      { type: 'p', text: "Broad match is Google's default keyword setting — and it's designed to spend your money. When you add a keyword like \"roof repair\" on broad match, Google can show your ad to anyone searching \"roof contractor license requirements,\" \"roof repair DIY guide,\" or even \"roof replacement insurance claim help.\" These searchers are not your customers." },
      { type: 'p', text: "The fix: Switch to phrase match or exact match for your core keywords. Use broad match only with a strong negative keyword list in place, and only if you're actively reviewing search term reports weekly." },
      { type: 'h2', text: 'Mistake #2: No Negative Keyword List' },
      { type: 'p', text: "Negative keywords tell Google which searches should NOT trigger your ad. Without them, your $1,500/month budget bleeds out on irrelevant clicks. The most common negatives we add immediately in every account:" },
      { type: 'ul', items: ['\"free,\" \"DIY,\" \"how to,\" \"tutorial\"', '\"jobs,\" \"careers,\" \"hiring\"', '\"reviews\" or \"complaints\" (unless you want reputation traffic)', '\"near me\" if you only serve specific zip codes', 'Competitor brand names (unless you\'re running a conquest campaign)'] },
      { type: 'p', text: "A single audit session building a solid negative keyword list can cut wasted spend by 20–40% overnight." },
      { type: 'h2', text: 'Mistake #3: Sending Traffic to Your Homepage' },
      { type: 'p', text: "This is the most expensive mistake we see. When someone searches \"emergency plumber Daytona Beach\" and clicks your ad, they land on your homepage — with a nav bar, 6 sections, and no clear next step. They bounce within 10 seconds." },
      { type: 'p', text: "Every Google Ads campaign should drive to a dedicated landing page that matches the exact search intent. That page should have one goal: get the visitor to call or fill out a form. No distractions, no navigation bar, no competing messages." },
      { type: 'callout', title: 'The Rule We Follow', text: 'Ad message → Landing page headline → Form or phone call. Every element on the page exists to push toward that single conversion.' },
      { type: 'h2', text: 'Mistake #4: Conversion Tracking Is Broken (or Not Set Up)' },
      { type: 'p', text: "You cannot optimize what you don't measure. Google Ads without conversion tracking is like running a store with no cash register — you don't know what's selling." },
      { type: 'p', text: "We've audited accounts that had been running for 12+ months with zero conversion tracking. The client had no idea which keywords, ads, or campaigns were actually generating calls and leads. They were just watching the budget drain." },
      { type: 'p', text: "Minimum conversion tracking setup: phone call tracking (via CallRail or Google Ads call extensions), form submission confirmation page tracking, and if relevant, Google Business Profile call tracking. All three, tracked separately." },
      { type: 'h2', text: 'Mistake #5: Ad Copy That Doesn\'t Match Search Intent' },
      { type: 'p', text: "Your ad copy needs to echo exactly what the searcher typed. If someone searches \"best screen enclosure company Daytona Beach\" and your ad headline says \"Screen Enclosures | Quality Work\" — you're missing the match. A better headline: \"Best-Rated Screen Enclosures in Daytona Beach — Free Estimate.\"" },
      { type: 'p', text: "The more your ad reads like a direct answer to the search query, the higher your Quality Score, the lower your cost per click, and the higher your conversion rate. It's a compounding advantage." },
      { type: 'h2', text: 'The Fix: Our 5-Step Audit Process' },
      { type: 'p', text: "When we take on a new Google Ads account, here's what happens in the first 30 days:" },
      { type: 'ul', items: ['Full account audit — keyword match types, search term reports, conversion tracking review', 'Negative keyword build-out based on 30-day search term data', 'Landing page audit and rewrite if needed', 'Ad copy test matrix — 2–3 variations per ad group', 'Weekly optimization cadence: bid adjustments, audience layering, quality score improvements'] },
      { type: 'p', text: "Within 60 days, most clients see their cost per lead drop by 30–50% just from fixing the structural issues — before we've even run a single new test." },
      { type: 'callout', title: 'Want a Free Audit?', text: "We'll review your current Google Ads account and show you exactly where budget is being wasted. No charge, no commitment — just a clear picture of what's working and what isn't." },
    ],
  },
  {
    slug: 'dominate-google-maps-90-days',
    title: 'How to Dominate Google Maps in Your City in 90 Days',
    desc: "The GBP strategy we used to land 3 clients in the local pack within 3 months. Step-by-step for Florida service businesses.",
    cat: 'Local SEO',
    date: 'April 18, 2026',
    isoDate: '2026-04-18',
    readTime: '7 min read',
    iconColor: '#16a34a',
    bg: '#f0fdf6',
    relatedService: { label: 'Local SEO', href: '/services/seo' },
    metaTitle: 'How to Dominate Google Maps in 90 Days',
    metaDesc: 'A step-by-step Google Business Profile strategy to rank in the local map pack within 90 days — used by NXT Level Builds for clients across Daytona Beach and Volusia County.',
    body: [
      { type: 'p', text: "Google Maps ranking (also called the \"local pack\") is the most valuable real estate for any service business. When someone searches \"electrician near me\" or \"web design Daytona Beach,\" the three businesses shown in the map section get the majority of clicks — often 70%+ of all search traffic." },
      { type: 'p', text: "Here's the exact process we used to move three of our clients into the local pack within 90 days of working together." },
      { type: 'h2', text: 'Step 1: Fully Complete Your Google Business Profile (Most People Skip This)' },
      { type: 'p', text: "Most GBP listings are 40–60% complete. Google rewards completeness. Go through every single field:" },
      { type: 'ul', items: ['Business name (exactly as it appears legally — no keyword stuffing)', 'Primary and secondary categories (choose the most specific primary category available)', 'Business hours (including holiday hours)', 'Phone number with local area code', 'Website URL', 'Service area (list every city and zip code you serve)', 'Products/Services with descriptions and prices', 'Business description (750 characters — use naturally)'] },
      { type: 'p', text: "Add photos — at minimum 10 high-quality photos of your work, your team, and your location. Businesses with 10+ photos get significantly more clicks than those with 1–3." },
      { type: 'h2', text: 'Step 2: Build Consistent NAP Citations' },
      { type: 'p', text: "NAP stands for Name, Address, Phone number. Google cross-references your business information across dozens of directory sites to verify legitimacy. Inconsistency (\"NXT Level Builds\" vs \"NXT Level Builds LLC\" vs \"NXT Level\") is a ranking penalty." },
      { type: 'p', text: "Priority citation sources for Florida businesses: Yelp, Facebook Business Page, Bing Places, Apple Maps, BBB, Chamber of Commerce local chapter, HomeAdvisor or Thumbtack (if applicable to your trade)." },
      { type: 'callout', title: 'Pro Tip', text: 'Use the exact same phone number, address format, and business name across every single directory — including punctuation and abbreviations. Audit this every 6 months.' },
      { type: 'h2', text: 'Step 3: Reviews — Volume and Velocity Both Matter' },
      { type: 'p', text: "Google's algorithm rewards both the total number of reviews and the pace at which you receive them. A business with 5 reviews in the last 30 days will often outrank a competitor with 200 reviews and no new ones for 6 months." },
      { type: 'p', text: "The best review acquisition strategy: send a direct link to your Google Review page via text immediately after completing a job. Response rates are highest within 2 hours of service completion. We automate this for clients using GoHighLevel — every completed job triggers a review request text and follow-up." },
      { type: 'h2', text: 'Step 4: Post to Your GBP Weekly' },
      { type: 'p', text: "Google Business Profile has a \"Posts\" feature — it's essentially a social feed attached to your listing. Most businesses never use it. Weekly posts (showcasing completed jobs, promotions, or tips) signal to Google that your listing is active." },
      { type: 'p', text: "Post format that works: a photo of the completed project + a short description with the city name and service type + a call to action. \"Just finished a screen enclosure in Port Orange — free estimates available this week.\"" },
      { type: 'h2', text: 'Step 5: Build Local Backlinks' },
      { type: 'p', text: "Links from other Daytona Beach or Volusia County websites point to your site and signal local authority. The best sources: local news coverage (Daytona Beach News-Journal, Volusia News), local business associations, sponsor a local event and get listed on their site, and get featured in local business directories." },
      { type: 'h2', text: 'What 90 Days Looks Like' },
      { type: 'p', text: "Month 1: Profile completion, citation audit and cleanup, review acquisition system launched. Month 2: First local backlinks, weekly posting routine, Q&A section populated. Month 3: First movement in rankings, conversion rate optimizations to the listing (photos, offer posts)." },
      { type: 'p', text: "One of our clients, a pool screening company in Daytona Beach, moved from page 3 to the local pack (#2 position) within 67 days using this exact process. Their inbound call volume from Google Maps went up 190%." },
    ],
  },
  {
    slug: '5-things-automate-with-ai',
    title: '5 Things Small Businesses Can Automate With AI Right Now',
    desc: 'Workflows saving clients 10+ hours a week — starting this week. No technical background required.',
    cat: 'AI Automation',
    date: 'April 5, 2026',
    isoDate: '2026-04-05',
    readTime: '6 min read',
    iconColor: '#7c3aed',
    bg: '#f5f3ff',
    relatedService: { label: 'AI Automation', href: '/services/ai-automation' },
    metaTitle: '5 Things to Automate With AI for Small Businesses',
    metaDesc: 'Save 10+ hours a week with these 5 AI automation workflows. Lead follow-up, appointment booking, review requests, and more — practical and ready to deploy.',
    body: [
      { type: 'p', text: "\"AI automation\" sounds expensive and complicated. It's not. The workflows we build for clients often take 1–2 days to set up and start saving them 8–15 hours a week immediately." },
      { type: 'p', text: "Here are 5 specific automations that work for small service businesses — explained plainly, with no technical jargon." },
      { type: 'h2', text: '1. Lead Follow-Up (The Biggest ROI Automation Possible)' },
      { type: 'p', text: "The average business takes 47 hours to follow up with a new lead. Studies show that if you respond within 5 minutes, you're 9× more likely to convert that lead. Waiting 24+ hours drops your conversion rate by over 80%." },
      { type: 'p', text: "The automation: When a lead fills out your contact form (or calls and doesn't get answered), they get an instant text and email: \"Hey, this is [Business Name] — got your message. Give me 10 minutes and I'll call you back.\" This alone dramatically increases show rates and reply rates." },
      { type: 'p', text: "Tools: GoHighLevel, Make.com, or Zapier connected to your CRM. Setup time: 4–6 hours." },
      { type: 'h2', text: '2. Appointment Booking Without Back-and-Forth' },
      { type: 'p', text: "For businesses that rely on booked appointments — consultations, estimates, service calls — the scheduling back-and-forth is a massive time drain. \"What time works for you?\" \"How about Tuesday?\" \"Tuesday doesn't work, what about Thursday?\"" },
      { type: 'p', text: "The automation: A Calendly or GoHighLevel booking link sent automatically after a lead inquiry. They pick a time from your real availability, confirmation is sent automatically, reminders go out 24 hours and 1 hour before. You show up to calls that are already confirmed — no coordination needed." },
      { type: 'callout', title: 'Real Impact', text: "One of our clients (a fitness coaching brand) went from booking 40 consultations a month manually to 82 per month after we automated their scheduling and follow-up system. Same leads, same budget — just no lost opportunities." },
      { type: 'h2', text: '3. Review Request Sequences' },
      { type: 'p', text: "Most businesses lose reviews because they forget to ask — or they ask awkwardly in person. Automated review requests sent via text 2–3 hours after job completion get 3–5× more reviews than manual asking." },
      { type: 'p', text: "The automation: Job marked as complete in your CRM → triggers a text to the customer → text includes your direct Google Review link → 24-hour follow-up if no action taken. Simple, effective, runs without you touching it." },
      { type: 'h2', text: '4. Re-Engagement Sequences for Old Leads' },
      { type: 'p', text: "Most businesses have a graveyard of leads in their CRM — people who inquired, got busy, and went cold. These people already know your business. They're far easier to convert than brand-new leads." },
      { type: 'p', text: "The automation: A 3-email or 3-text sequence that goes out to any lead that's been inactive for 30+ days. Message 1: a \"just checking in\" touchpoint. Message 2: a case study or result. Message 3: a time-limited offer or CTA." },
      { type: 'h2', text: '5. Onboarding New Clients Without Manual Effort' },
      { type: 'p', text: "Once a lead signs and pays, there's a whole onboarding process: intake forms, contract delivery, welcome emails, first meeting scheduling, and document collection. Done manually for every client, this takes 2–3 hours per onboarding." },
      { type: 'p', text: "The automation: Payment confirmed → CRM tags client as \"Active\" → triggers onboarding sequence: welcome email, intake form link, contract for e-signature, calendar booking for kickoff call. All within 5 minutes of payment. Zero manual work." },
      { type: 'h2', text: 'Where to Start' },
      { type: 'p', text: "If you're implementing these yourself, start with #1 (lead follow-up) — it has the fastest ROI and affects every lead coming into your business. If you want a full system built and deployed, that's exactly what we do at NXT Level Builds." },
    ],
  },
  {
    slug: 'website-losing-customers',
    title: "Why Your Website Is Losing You Customers Without You Knowing",
    desc: 'Page speed, trust signals, and above-the-fold copy — the silent conversion killers that most business owners never check.',
    cat: 'Web Design',
    date: 'March 22, 2026',
    isoDate: '2026-03-22',
    readTime: '5 min read',
    iconColor: '#ea580c',
    bg: '#fff7ed',
    relatedService: { label: 'Custom Web Design', href: '/services/web-design' },
    metaTitle: 'Why Your Website Is Losing Customers',
    metaDesc: 'Most business websites kill conversions silently. Here are the 5 most common reasons your website is costing you leads — and what to fix first.',
    body: [
      { type: 'p', text: "You paid for a website. You have a website. And you assume it's working for your business. But for most small business websites we audit, the site is quietly driving away customers every day — and the owner never knows because there's no tracking in place." },
      { type: 'p', text: "Here are the five silent conversion killers we find in almost every audit." },
      { type: 'h2', text: '1. Your Site Takes More Than 3 Seconds to Load' },
      { type: 'p', text: "53% of mobile users abandon a site that takes longer than 3 seconds to load. Not 10 seconds — 3 seconds. And yet the average small business website loads in 7–12 seconds on mobile." },
      { type: 'p', text: "How to check: Run your site through Google PageSpeed Insights (search for it). A score below 70 on mobile is a serious problem. Common culprits: unoptimized images, slow hosting, bloated WordPress plugins, no caching." },
      { type: 'callout', title: 'What We Target', text: "Every site we build scores 90+ on PageSpeed for both mobile and desktop. Speed isn't a feature — it's a baseline requirement for ranking and converting." },
      { type: 'h2', text: "2. Your Above-the-Fold Copy Doesn't Answer \"Why You?\"" },
      { type: 'p', text: "Above the fold means what a visitor sees before they scroll. You have about 5 seconds to convince them they're in the right place. Most business websites waste those 5 seconds with something like: \"Welcome to [Business Name].\" or \"Serving the community for over 20 years.\"" },
      { type: 'p', text: "These statements answer nobody's question. A visitor arrives asking: \"Can this business solve my specific problem quickly and reliably?\" Your headline needs to answer that — specifically, confidently, and immediately." },
      { type: 'p', text: "Compare: \"Welcome to Mike's Roofing\" vs \"Daytona Beach Roof Repairs — Licensed, Fast, 5-Star Rated. Free Estimate in 24 Hours.\" One converts. One doesn't." },
      { type: 'h2', text: '3. No Clear Call to Action' },
      { type: 'p', text: "When a visitor decides they want to reach out, they should find a button or phone number immediately — without scrolling or hunting. If they have to look for contact info, most won't." },
      { type: 'p', text: "The fix: Your phone number should be in the top navigation bar, clickable on mobile. Every section of your homepage should have a visible CTA. Your primary button should be a single, specific action: \"Call Now,\" \"Get a Free Estimate,\" or \"Book a Consultation\" — not \"Contact Us.\"" },
      { type: 'h2', text: '4. Your Site Has No Trust Signals' },
      { type: 'p', text: "Would you hire a contractor you know nothing about? Of course not. Your website visitors feel the same way. Trust signals are anything that helps a stranger trust your business: Google review count and rating, number of years in business, licenses and certifications, real photos of your work, and a visible face or name." },
      { type: 'p', text: "A site with \"Over 50 5-Star Google Reviews\" and a real photo of the owner converts at 2–3× the rate of a generic site with no social proof." },
      { type: 'h2', text: '5. Your Site Isn\'t Mobile-First' },
      { type: 'p', text: "Over 70% of local service searches happen on a phone. If your website is hard to use on mobile — small text, wide tables, tiny buttons, forms that don't work — you're losing the majority of your potential customers before they even read your offer." },
      { type: 'p', text: "Test it right now: open your site on your phone. Can you read it without zooming? Can you tap the call button in the first 2 seconds? If not, you have a problem that's costing you real money every day." },
    ],
  },
  {
    slug: 'lsa-vs-google-search-ads',
    title: 'LSA vs Google Search Ads: Which One Is Right for Your Business?',
    desc: 'A side-by-side breakdown for Florida service businesses. When to use each — and when to run both.',
    cat: 'Google Ads',
    date: 'March 10, 2026',
    isoDate: '2026-03-10',
    readTime: '6 min read',
    iconColor: '#dc2626',
    bg: '#fff1f0',
    relatedService: { label: 'Google Ads Management', href: '/services/google-ads' },
    metaTitle: 'LSA vs Google Search Ads: Which Is Right for Your Business?',
    metaDesc: 'Local Services Ads vs Google Search Ads — a plain-English comparison for Florida service businesses. Learn which one drives better ROI and when to use both.',
    body: [
      { type: 'p', text: "If you run a service business in Florida, you've likely heard about both Local Services Ads (LSA) and Google Search Ads — and you might be wondering which one is actually worth your budget. They look similar but they work very differently." },
      { type: 'h2', text: 'What Are Local Services Ads (LSA)?' },
      { type: 'p', text: "Local Services Ads show up at the very top of Google — above regular Search Ads and above organic results. They're formatted as a small box showing your business name, rating, number of reviews, and a \"Google Guaranteed\" or \"Google Screened\" badge." },
      { type: 'p', text: "The key difference: with LSA, you pay per lead, not per click. If someone calls you directly from your LSA listing, you pay for that call. If they click and don't call, you pay nothing." },
      { type: 'ul', items: ['Available for: contractors, plumbers, electricians, HVAC, cleaning services, locksmiths, pest control, movers, and more', 'Requires: background check, license verification, and insurance verification', 'Billing: per lead (Google defines what counts as a qualifying lead)', 'Dispute: you can dispute invalid leads and get credit back'] },
      { type: 'h2', text: 'What Are Google Search Ads?' },
      { type: 'p', text: "Google Search Ads are the text-based ads that appear when someone searches a keyword. You pay per click — whether that click converts or not. You have full control over ad copy, keywords, landing pages, and bidding strategy." },
      { type: 'ul', items: ['Available for: any business or service', 'Requires: Google Ads account, landing page, and campaign setup', 'Billing: per click (cost varies by keyword competition — can be $3–$80 per click in competitive trades)', 'Control: full control over targeting, copy, and landing experience'] },
      { type: 'h2', text: 'Head-to-Head Comparison' },
      { type: 'ul', items: ['Cost model: LSA = per lead | Search Ads = per click', 'Setup complexity: LSA = simple (1–2 days) | Search Ads = complex (1–2 weeks properly)', 'Control: LSA = limited | Search Ads = full control', 'Placement: LSA = absolute top | Search Ads = just below LSA', 'Trust badge: LSA = Google Guaranteed | Search Ads = no badge', 'Best for: LSA = high-volume service businesses | Search Ads = specific offers, seasonal campaigns, any industry'] },
      { type: 'h2', text: 'Which One Should You Run?' },
      { type: 'p', text: "For most Florida service businesses (contractors, home services, trades), our recommendation is: run both, but understand the role of each." },
      { type: 'p', text: "LSA is your baseline trust play — it drives calls directly from the top of the page, and the Google Guaranteed badge converts skeptical searchers. Start here if you're in an eligible category and want the simplest path to inbound calls." },
      { type: 'p', text: "Google Search Ads give you scale and control. Once you have conversion tracking in place and a solid landing page, Search Ads let you target specific services, zip codes, time-of-day, and device types. You can push harder during peak season and pull back in slow periods." },
      { type: 'callout', title: 'Our Setup for Most Clients', text: 'LSA running 24/7 for brand credibility and consistent lead flow. Search Ads targeting 3–5 high-intent keywords with dedicated landing pages for each. Together they dominate the top of the search results page.' },
      { type: 'h2', text: 'The One Mistake to Avoid' },
      { type: 'p', text: "Don't run Search Ads without conversion tracking. You'll spend $1,000–$2,000 before you know if anything is working. Set up CallRail or Google Ads call tracking before you launch a single Search Ads campaign." },
    ],
  },
  {
    slug: 'link-building-2026',
    title: "Link Building in 2026: What Still Works and What's a Waste of Time",
    desc: 'We tested a dozen strategies. Here is the short list that actually moves rankings — and the ones that are just noise.',
    cat: 'SEO',
    date: 'Feb 28, 2026',
    isoDate: '2026-02-28',
    readTime: '9 min read',
    iconColor: '#1a6eff',
    bg: '#eef3ff',
    relatedService: { label: 'Local SEO', href: '/services/seo' },
    metaTitle: 'Link Building in 2026: What Works vs. What Wastes Time',
    metaDesc: "Link building in 2026 is different. Here's what still works for local and small business SEO — and what's a complete waste of time.",
    body: [
      { type: 'p', text: "Link building has evolved more than any other part of SEO over the past 5 years. Tactics that used to work reliably — guest post networks, directory spam, private blog networks — are now either useless or actively harmful. Meanwhile, the tactics that do work are more accessible than ever for local businesses." },
      { type: 'p', text: "After running SEO for businesses across Daytona Beach and Florida, here's our honest take on what moves rankings in 2026." },
      { type: 'h2', text: 'What Actually Works' },
      { type: 'h3', text: 'Local Business Citations (Still Foundational)' },
      { type: 'p', text: "For local businesses, citations — consistent NAP (name, address, phone) listings across directories — still matter. Yelp, Bing Places, Apple Maps, BBB, and local Chamber of Commerce listings are all valuable. They don't carry as much ranking power as editorial links, but they're quick to build and directly support your Google Business Profile trust signals." },
      { type: 'h3', text: 'Digital PR and Local News Coverage' },
      { type: 'p', text: "A mention in the Daytona Beach News-Journal, a Volusia County business profile, or a feature in a local chamber newsletter — these are high-authority local links that are genuinely hard to fake. The way to earn them: do something newsworthy (hire, expand, win an award, sponsor a community event), and proactively pitch local journalists." },
      { type: 'h3', text: 'Supplier and Partner Links' },
      { type: 'p', text: "If you're a contractor who uses a specific material supplier, ask if they have a \"local contractors\" page or dealer locator. If you're a member of a professional association, make sure you're listed on their website with a link. These links are relevant, authoritative, and already available — you just have to ask." },
      { type: 'h3', text: 'Resource Links From Real Content' },
      { type: 'p', text: "Content that solves a real problem gets linked to. Write a genuinely useful guide — \"How to Choose a Roofing Contractor in Florida\" or \"What to Look for in a Screen Enclosure\" — and it will earn links over time without any outreach. Especially if it's the best resource on that specific topic." },
      { type: 'h2', text: "What's a Waste of Time" },
      { type: 'h3', text: 'Guest Post Networks' },
      { type: 'p', text: "If you're paying $50–$200 per \"guest post\" on a site that exists only to publish guest posts, Google already knows. These links carry near-zero value and create a pattern in your backlink profile that can trigger manual review." },
      { type: 'h3', text: 'Generic Directory Spam' },
      { type: 'p', text: "Submitting to 500 free directories that have nothing to do with your industry or location is pointless. Google doesn't count links from sites with no traffic, no editorial standards, and no relevance to your business." },
      { type: 'h3', text: 'Buying Links' },
      { type: 'p', text: "Purchased links from link brokers or private blog networks (PBNs) are a violation of Google's guidelines. When (not if) Google identifies these, the penalty can set your rankings back months or years. The short-term gain is never worth the risk for a local business that depends on organic traffic." },
      { type: 'callout', title: 'The 2026 Framework', text: 'Focus 80% of your link building effort on: citations (fast to build), local press (high authority), and partner/supplier links (low effort). Spend the other 20% creating genuinely helpful content that earns links passively.' },
      { type: 'h2', text: 'How Many Links Do You Actually Need?' },
      { type: 'p', text: "For most local businesses competing in Volusia County or a comparable market, you don't need hundreds of links. You need 20–30 quality, relevant, local links. Check your top-ranking competitor's backlink profile in Ahrefs or SEMrush — for most local service searches, the #1 result has fewer than 50 referring domains." },
      { type: 'p', text: "Quality beats quantity every time in local SEO. One link from the Daytona Beach News-Journal is worth more than 100 links from random directories." },
    ],
  },
  {
    slug: 'how-much-small-business-spend-marketing',
    title: 'How Much Should a Small Business Spend on Digital Marketing?',
    desc: 'A practical framework based on revenue, goals, and market competition. No generic percentages — a real answer.',
    cat: 'Business',
    date: 'Feb 14, 2026',
    isoDate: '2026-02-14',
    readTime: '5 min read',
    iconColor: '#16a34a',
    bg: '#f0fdf6',
    relatedService: { label: 'Free Strategy Call', href: '/contact' },
    metaTitle: 'How Much Should a Small Business Spend on Digital Marketing?',
    metaDesc: 'A practical framework for setting your digital marketing budget — based on revenue goals and competition, not generic percentages.',
    body: [
      { type: 'p', text: "\"What should I budget for digital marketing?\" is the most common question we get on initial calls. And the honest answer is: it depends. But \"it depends\" isn't useful — so here's a real framework." },
      { type: 'h2', text: "Start With Revenue, Not Percentages" },
      { type: 'p', text: "You'll see advice saying \"spend 5–10% of revenue on marketing.\" That's fine for a Fortune 500 company managing stable revenue. For a growing small business, it's the wrong way to think about it." },
      { type: 'p', text: "Better question: what is a new customer worth to your business? If a new roofing job is worth $8,000 and you close 1 in 3 leads, then you can afford to spend up to $2,600 per lead and break even on the first job. Factor in lifetime value (they call you for repairs, refer friends) and you can afford more." },
      { type: 'callout', title: 'The Math', text: 'Customer Lifetime Value ÷ Average Close Rate = Max Cost Per Lead. This is your ceiling. Build your budget from here, not from a generic percentage.' },
      { type: 'h2', text: 'Budget by Goal' },
      { type: 'h3', text: "Goal: Get Found Locally (0–$1,000/month)" },
      { type: 'p', text: "Priority: Google Business Profile optimization, basic website SEO, citation building. This is the foundation — it doesn't cost much to execute but takes 3–6 months to compound. If you're starting from nothing, start here." },
      { type: 'h3', text: "Goal: Generate Consistent Leads ($1,000–$2,500/month)" },
      { type: 'p', text: "Priority: Google Ads (budget: $800–$1,500 for ad spend, $400–$600 for management), plus continued SEO. This range can generate 15–40 qualified leads per month depending on your market and average ticket size." },
      { type: 'h3', text: "Goal: Dominate Your Market ($2,500–$5,000/month)" },
      { type: 'p', text: "Priority: Aggressive local SEO, full Google Ads management (LSA + Search), a content strategy, and potentially social media ads. At this level you're playing offense — building brand recognition and capturing market share." },
      { type: 'h2', text: "What Kills Marketing Budgets" },
      { type: 'ul', items: ["Spending on ads without a conversion-optimized landing page — you're paying for traffic that won't convert", "Paying for \"SEO\" that's just directory submissions and no real content strategy", "Starting ads without conversion tracking — you can't optimize what you can't measure", "Treating marketing as a one-time project instead of an ongoing investment"] },
      { type: 'h2', text: "What We'd Do With $1,000/Month" },
      { type: 'p', text: "For a service business in Daytona Beach or Volusia County: $600 in Google Ads spend targeting 3–5 high-intent keywords, $400 for monthly management and optimization, plus Google Business Profile optimization running in the background." },
      { type: 'p', text: "At that spend level, with a well-structured campaign and solid landing page, most clients see 10–20 qualified leads per month. If your average job is $1,500+, the math works from day one." },
    ],
  },
  {
    slug: 'web-design-vs-web-development',
    title: "Web Design vs Web Development: What's the Difference and What Do You Actually Need?",
    desc: "Most people use these terms interchangeably — they're not the same. Here's the plain-English breakdown and how to know what to hire for.",
    cat: 'Web Design',
    date: 'Jan 30, 2026',
    isoDate: '2026-01-30',
    readTime: '5 min read',
    iconColor: '#ea580c',
    bg: '#fff7ed',
    relatedService: { label: 'Custom Web Design', href: '/services/web-design' },
    metaTitle: 'Web Design vs Web Development: What Do You Actually Need?',
    metaDesc: "Web design and web development are not the same thing. Here's the plain-English breakdown — and what a small business actually needs to get a site that converts.",
    body: [
      { type: 'p', text: "If you've ever shopped for a website, you've seen both terms: web design and web development. Sometimes they're used interchangeably. Sometimes agencies offer both under one umbrella. And most business owners aren't sure what they actually need or what they're paying for." },
      { type: 'p', text: "Here's the clear breakdown." },
      { type: 'h2', text: 'Web Design: How a Site Looks and Feels' },
      { type: 'p', text: "Web design covers the visual layer: colors, typography, layout, spacing, imagery, icons, and the overall user experience. A web designer answers: \"Does this site look professional? Is it clear what this business does? Can a visitor find what they need in under 10 seconds?\"" },
      { type: 'p', text: "Good web design is conversion-focused. It's not just making something look pretty — it's making something that moves people from \"I found this site\" to \"I'm calling this business.\"" },
      { type: 'h2', text: 'Web Development: How a Site Works' },
      { type: 'p', text: "Web development is the code behind the design. It's what makes buttons work, forms submit, pages load fast, and databases update. A developer answers: \"Is this site technically sound? Does it perform well? Is the code clean and maintainable?\"" },
      { type: 'p', text: "There are two types: front-end development (the client-facing code — HTML, CSS, JavaScript) and back-end development (the server, database, and application logic). Most small business sites only need front-end development." },
      { type: 'h2', text: 'What a Small Business Actually Needs' },
      { type: 'p', text: "For a typical 5–10 page service website, you need both — but in a specific ratio. You need excellent design (this drives conversions) and solid front-end development (this ensures it actually works, loads fast, and ranks on Google). You almost never need back-end development unless you're building an e-commerce store or a client portal." },
      { type: 'callout', title: 'The Problem With Most Agencies', text: 'Many agencies either charge for \"full-stack development\" when you only need a marketing site, or they deliver pretty designs built on slow WordPress templates that hurt your SEO. Ask for both capabilities and make sure they work together.' },
      { type: 'h2', text: 'The Framework We Use' },
      { type: 'p', text: "At NXT Level Builds, every website starts as a custom design (built in Figma or delivered as a live prototype for approval) before a single line of code is written. The development phase uses Next.js — a React framework that's faster than WordPress, cleaner than page builders, and built for performance." },
      { type: 'p', text: "The result: a site that looks intentional, loads under 2 seconds on mobile, and is optimized for conversion from the first day it's live." },
    ],
  },
  {
    slug: 'diy-website-vs-hiring-agency',
    title: 'DIY Website vs Hiring an Agency: The True Cost Comparison',
    desc: 'Squarespace looks cheap until you factor in your time, lost leads, and the cost of a site that never converts. Here\'s the honest math.',
    cat: 'Web Design',
    date: 'Jan 15, 2026',
    isoDate: '2026-01-15',
    readTime: '6 min read',
    iconColor: '#ea580c',
    bg: '#fff7ed',
    relatedService: { label: 'Pricing & Packages', href: '/pricing' },
    metaTitle: 'DIY Website vs Hiring a Web Design Agency | True Cost Comparison',
    metaDesc: "Is a DIY website (Squarespace, Wix, GoDaddy) actually cheaper than hiring an agency? Here's the true cost comparison — including what most people don't factor in.",
    body: [
      { type: 'p', text: "\"I'll just build it on Squarespace\" is something we hear from prospective clients all the time. And honestly? For some businesses, it's the right call. But for most small businesses trying to generate leads and rank on Google, the math doesn't add up the way people think." },
      { type: 'p', text: "Here's a real comparison." },
      { type: 'h2', text: 'The True Cost of DIY' },
      { type: 'h3', text: 'Time' },
      { type: 'p', text: "Building a website on Squarespace or Wix takes most business owners 30–80 hours. That's choosing a template, writing copy, uploading photos, configuring forms, and dealing with everything that doesn't work right. At $50/hour (a conservative value of your time), that's $1,500–$4,000 in opportunity cost." },
      { type: 'h3', text: 'Ongoing Fees' },
      { type: 'p', text: "Squarespace Business: $23/month. Custom domain: $20/year. Stock photo subscriptions, email marketing tools, booking software, popup builders, SEO plugins — it adds up. Most small businesses end up paying $400–$700/year in SaaS subscriptions on top of their website platform fee." },
      { type: 'h3', text: 'Performance and SEO' },
      { type: 'p', text: "Template-based builders consistently score 40–65 on Google PageSpeed for mobile. Slow sites rank lower on Google and convert worse. The leads you don't get because your site is slow or doesn't rank are the invisible cost of DIY — and it's often the biggest one." },
      { type: 'callout', title: 'The Real Hidden Cost', text: "Every month your site doesn't convert costs you leads. If your DIY site loses you 3 jobs per month at $1,500 each — that's $4,500 in lost revenue per month. The $997 website pays for itself in the first week." },
      { type: 'h2', text: 'When DIY Makes Sense' },
      { type: 'p', text: "We'll say it plainly: DIY is fine if your business doesn't depend heavily on online leads, if you're a solo freelancer or creator validating an idea, or if you need something live in 48 hours and conversion isn't critical yet." },
      { type: 'p', text: "If you're a service business that depends on Google search traffic and inbound inquiries, DIY is rarely the right call once you factor everything in." },
      { type: 'h2', text: 'What You Actually Get With an Agency' },
      { type: 'p', text: "A professionally built site from NXT Level Builds costs $997 for a 5-page site. It loads under 2 seconds, scores 90+ on PageSpeed, is built for local SEO from day one, and includes a lead capture form connected to your CRM. It's live in 7 days." },
      { type: 'p', text: "Compare that to spending 60 hours of your time, paying $600/year in tools, and ending up with a site that scores 55 on mobile speed and doesn't rank for anything." },
      { type: 'h2', text: 'The Honest Bottom Line' },
      { type: 'p', text: "The cheapest website isn't the one with the lowest price tag. It's the one that costs the least per lead generated. A $997 custom site that generates 10 qualified leads per month is 10× cheaper than a free website that generates 1." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find(p => p.slug === slug);
}

export function getRelatedPosts(slug: string, count = 3): Post[] {
  const current = getPost(slug);
  if (!current) return posts.slice(0, count);
  return posts.filter(p => p.slug !== slug && p.cat === current.cat).slice(0, count).concat(
    posts.filter(p => p.slug !== slug && p.cat !== current.cat)
  ).slice(0, count);
}
